services:
  - type: web
    name: news-chatbot-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_API_URL
        value: https://news-chatbot-backend.onrender.com
